server:
  port: 8081

spring:
  # JPA 설정
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddlAuto: create

security:
  oauth2:
    client:
      provider:
        external:
          issuerUri: http://localhost:8073/realms/spmia-realm  # 생성된 realm 이름

      registration:
        external:
          - provider: external
          - clientName: choongang
          - clientId: choongang
          - clientSecret: JYDIcb8LnAjWsnEL9DerhTdJ1ox4dd0m
          - scope: openid,offline_access,profile
          - authorizationGrantType: authorization_code

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
